services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        volumes:
            - ./data/:/opt/alist/data
            - ./data/files/:/opt/files
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped
        env_file:
        - .env
    tunnel:
        restart: unless-stopped
        image: cloudflare/cloudflared
        command: tunnel run
        env_file:
        - .env
